export const heroParagraph1 = 'There were 59.1 million people living in internal displacement worldwide at the end of 2021, the highest figure on record.  The exact number of children among them is unknown, but there are estimated to be about 9.9 million aged between five and 11, and 7.5 million between 12 and 17.';
export const heroParagraph2 = 'These children are particularly invisible for two reasons. Internally displaced people (IDPs) of all ages are largely unaccounted for compared with refugees and migrants, and little data of any kind is disaggregated by age, let alone that on IDPs.';
export const heroParagraph3 = 'This report represents a first step towards bridging these knowledge gaps. It provides an overview of the data landscape on IDPs’ education and top-line estimates of the number of internally displaced boys and girls of school age in 13 countries: Afghanistan, Colombia, the Democratic Republic of the Congo (DRC), Ethiopia, Iraq, Mozambique, Myanmar, Nigeria, Somalia, South Sudan, Sudan, Syria and Yemen.';
export const heroParagraph4 = 'It explores different data sources and methodologies to measure IDPs’ access to education, and the cost of providing them with education support. It concludes by outlining promising practices and ways forward in improving the collection and use of reliable, timely and comparable data to inform effective interventions.';

export const youngGirlCaption = 'A young girl walks home from school in ldlib, Syria amongst the debris and ruins of the war. ©OCHA/AliHaj';
export const youngGirlSubCaption = 'Suleiman, November 2021';

export const studingCaption = 'In the Nuevo Golfo neighbourhood of Barranquilla, Colombia, two sisters have been able to continue their education remotely.';
export const studingSubCaption = '© UNICEF/UN0413033/Romero, September 2020';

export const oldWallCaption = 'Only the walls, covered in bullet holes, of a local school on Erebiti, Ethiopia are left standing following conflict.';
export const oldWallSubCaption = '© OCHA/ Liz Loh-Taylor, July 2022';

export const primarySchoolCaption = 'Outside Darwish Primary School in Garowe, Somalia students read for one of their classes.';
export const primarySchoolSubCaption = '© UNICEF/UN0556449/Knowles-Coursin, November 2021';

export const childrenCaption = 'In a displacement site in the Ngote, Mahagi Territory of the Ituri Province in the Democratic Republic of Congo, a group of young boys looks ahead as class is being taught. ©Hugh Kinsella';
export const childrenSubCaption = 'Cunningham/NRC, April 2022.';
export const internallyDisplacedParagraph1 = 'Internally displaced children are largely unaccounted for because little data of any kind is disaggregated by age, let alone that on IDPs. Only about five per cent of the displacement records IDMC collected in 2021 included some form of age disaggregation. Quality, timely and comparable data on displaced children’s education is severely lacking. National governments are primarily responsible for the provision of education to IDPs and related data collection, but most do not monitor IDPs’ education status systematically. This may be due to capacity and resource constraints, political factors, and lack of coordination and data sharing. Local and international organisations collect data on IDPs’ education. They often use different methodologies and age groups, however, which makes it difficult to standardise and compare figures.';
export const internallyDisplacedParagraph2 = '“Data on internally displaced children is indispensable for designing better programmes and monitoring their effectiveness. Not knowing precisely how many children are displaced, where they are, or the nature of their education needs is a serious impediment to addressing the consequences of their plight on their current and future lives.”';
export const internallyDisplacedParagraph3 = 'Alexandra Bilak, Internal Displacement Monitoring Centre';

export const dataInternallyDisplacedDescription1 = 'The number of school-aged children internally displaced due to conflict, violence and disasters is unknown. IDMC has developed a methodology that uses national-level demographic data from the UN World Population Prospects to estimate the number of internally displaced boys and girls of a school age in the 13 countries selected for study. We applied the percentage of each country’s population by broad age groups and sex to the number of IDPs at the end of 2021 to obtain our figures. We used two broad age groups: five to 11 for pre-primary and primary school; and 12 to 17 for secondary school.';
export const dataInternallyDisplacedDescription2 = 'These numbers are likely to be conservative given IDMC’s figures of the total number of IDPs in each country are likely to be underestimates. Evidence from various countries also shows that the proportion of children among displaced populations is often higher than among the general population. Despite the limitations, the estimates give a sense of the scale of the issue. The fact that children represent more than 30 per cent of all IDPs across the 13 countries makes it clear that their experiences and needs cannot be ignore.';

export const estimatingEducationParagraph1 = '​Understanding the cost of providing quality education to internally displaced children is important to inform strategic planning and fundraising goals. Global and country-level data on education costs for children in general is limited, however, and even more so for IDPs. In the absence of more precise figures, IDMC has developed a methodology based on data from OCHA’s 2021 humanitarian response plans to estimate the cost of providing school-aged IDPs with education support in the 13 countries. This includes the cost of providing learning materials, school uniforms and temporary classrooms, and indirect costs linked with implementation and services delivery.';
export const estimatingEducationParagraph2 = 'For each country, we estimated the cost of providing education support for one internally displaced child for a year and then multiplied the figure by our estimates of the number of children aged five to 17 living in displacement at the end of 2021. We estimate that the average cost across the 13 countries falls between $81 and $93 per child, and that the total cost of providing support for all IDPs aged five to 17 is between $1.1 billion and $1.3 billion a year.​';
export const estimatingEducationParagraph3 = 'The cost estimates do not correspond to the humanitarian funding received, nor do they reflect actual expenditure on IDPs’ education. Rather, they are intended to represent the amount that humanitarian responders would have required to provide education support to all displaced children for a year.';
export const estimatedCaption = 'Estimated cost of providing education support for one internally displaced child and all school-aged IDPs in 13 countries';

export const qualityEducationParagraph1 = 'Displacement affects children’s education in many ways, reducing access and undermining equity, quality and the way it is managed. Schooling is most often interrupted, sometimes only for a few days or weeks, but in other cases for much longer. Cost is one of the most common barriers to education for IDPs, but language barriers, stigmatisation, psychological trauma and safety concerns are other common obstacles. Displaced girls tend to face heightened barriers to learning (see spotlight).';
export const qualityEducationParagraph2 = 'There are no internationally comparable figures on IDPs’ school attendance and completion, learning outcomes or out-of-school rates, but such information is vital to planning and costing effective responses. In absence of accurate, current and comparable figures, IDMC estimated the number of displaced children likely to be receiving education support or at risk of missing out on education in 13 countries based on information from OCHA’s humanitarian needs overviews and humanitarian response plans.';
export const qualityEducationParagraph3 = 'We estimate that more than nine million internally displaced children could be at risk of missing out on education because they did not receive support through humanitarian response plans in 2021. This does not, however, consider support they may be receiving directly from governments or other actors (see spotlight).';
export const descriptionCaption = 'Estimated number of school-aged IDPs across all 13 countries as of the end of 2021 by age group and sex';

export const qualityEducationQuote1 = '“In IDPs’ settlements, teenage girls stay at home and do chores. They are vulnerable to intimidation and harassment from the unstable environment they find themselves in, and their parents keep them at home because they are afraid for their safety.”';
export const qualityEducationQuote2 = 'Local youth representative, Beledweyne, Somalia';

export const wayForwardParagraph1 = 'Better data on internally displaced children would lay the foundation for transformative policies and programmes to ensure their access to quality education. The following action points should be considered to strengthen evidence based policymaking';

export const contactParagraph = 'IDMC’s Global Report on Internal Displacement (GRID) is the world’s leading source of data and analysis on internal displacement Since our establishment in 1998 as part of the Norwegian Refugee Council (NRC), we have offered a rigorous, independent and trusted service to the International community. Our work informs policy and operational decisions that improve the lives of the millions people living in intenal displacement, or at risk of becoming displaced in the future.';
export const copyrightParagraph = 'Copyright © Internal Displacement Monitoring Centre (IDMC). Unless otherwise indicated, all materials on this page may be shared freely providing an acknowledgement of IDMC as the source is included. Materials may not be adapted without prior permission from IDMC.';

export const conclusionDescription = 'Promising efforts are underway to address these data gaps. For example, the International Data Alliance for Children on the Move (IDAC) is an important initiative intended to foster streamlined approaches to improving statistics and data on displaced children. The Inter-agency Network for Education in Emergencies (INEE) is setting up the Data Reference Group on Education in Emergencies, which will bring together dozens of organisations that work on related topics to share their data, methodologies, approaches and experiences. Such examples reflect a growing awareness that strengthening data quality, sharing and interoperability is a priority in efforts to provide internally displaced children with quality education.';

export const reportLink = 'https://www.internal-displacement.org/sites/default/files/publications/documents/220919_IDMC_Disaster-Displacement-in-Asia-and-the-Pacific.pdf';
export const pressReleaseLink = 'https://www.internal-displacement.org/sites/default/files/220919_idmc_asiareport_pressrelease.pdf';

export const videoCaption = 'Disaster Displacements in the Asia and Pacific Region (2010−2021)';

export const mainQuote = '"Global efforts should be focused on reducing displacement risk and supporting durable solutions for those affected by disasters and the effects of climate change. Robust data on the scale, duration and severity of displacement will help guide future action, and critical knowledge and expertise can be shared with improved regional collaboration.”';
export const mainQuoter = 'Alexandra Bilak, Director Internal Displacement Monitoring Centre';

export const idmcAddress = 'Humanitarian Hub Office, La Voie Creuse 16, 1202 Geneva, Switzerland';
